# This is a basic workflow to help you get started with Actions

name: update submodules

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: update submodules
        run: |
          git submodule update --remote --recursive --init

      - name: push back
        run: |
          git config --global user.name 'Github Actions: submodule update'
          git config --global user.email jemand2001@users.noreply.github.com
          git commit -am rebuild || true
          git push
